### ISSUE TITLE
[VIEW] little inconcistency on view

### ISSUE THREAD

**Issue by nhomar** [Vauxoo/stock-forecasting#11]
![view](https://www.evernote.com/l/AJ7PhLQ6voRHlI2n-g0K3N1nmx_XWpHIOnsB/image.png)

**Comment by zaoral** [comment]
ok. working on it

**Comment by zaoral** [comment]
Task [vx#4016](https://www.vauxoo.com/web#id=4016&view_type=form&model=project.task&action=138) HU [913](https://www.vauxoo.com/web#id=913&view_type=form&model=user.story&action=726) Sprint 18
