### ISSUE TITLE
[IMP] name should be required.

### ISSUE THREAD

**Issue by nhomar** [Vauxoo/stock-forecasting#13]
![IMP](https://www.evernote.com/l/AJ5-TRMT2axLU4JNcX_Wfb_hf0DmpXIT6WUB/image.png)

**Comment by zaoral** [comment]
Task [vx#4016](https://www.vauxoo.com/web#id=4016&view_type=form&model=project.task&action=138) HU [913](https://www.vauxoo.com/web#id=913&view_type=form&model=user.story&action=726) Sprint 18
