### ISSUE TITLE
[IMP] Just installing the module do not give access to any configuration/option

### ISSUE THREAD

**Issue by nhomar** [Vauxoo/stock-forecasting#6]
Hello.

Just installing the module it is not clear how I can start to work with it, at least it should open explicitally the product menu (only).

**Comment by zaoral** [comment]
@nhomar I will start working on in it.
Best Regards

**Comment by nhomar** [comment]
Solution:

![Sol](https://www.evernote.com/l/AJ54Ef0-WN9JXo9UC9-YHnh_fHFGdVc-SjcB/image.png)

**Comment by nhomar** [comment]
IMPORTANT: 

Only need add such xml entry.

Yo do not need to work with other dependency.

**Comment by zaoral** [comment]
Task [vx#4016](https://www.vauxoo.com/web#id=4016&view_type=form&model=project.task&action=138) HU [913](https://www.vauxoo.com/web#id=913&view_type=form&model=user.story&action=726) Sprint 18
