### ISSUE TITLE
[DEMO] We need at least 1 product demo in order to not create it in the first test.

### ISSUE THREAD

**Issue by nhomar** [Vauxoo/stock-forecasting#7]
I see some test data when I just create a product, but the action should use the a domain with product_id on it.

If I just create a product manually (which should not be called test use other name) I expect see a blank list on forcasts.

**Comment by zaoral** [comment]
This issue was fixed and merged to 8.0 branch with commit 56afa33f65e5dd02bd7426acafc39fd1987851f1

**Comment by zaoral** [comment]
Missing edit the test name to a more mnemonic name.
